name: gwas_harm
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - pip>=24
  - tabix
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - bsub==0.3.5
      - certifi==2026.5.20
      - charset-normalizer==3.4.7
      - ConfigArgParse==1.7.5
      - datrie==0.8.3
      - duckdb==1.5.3
      - gitdb==4.0.12
      - GitPython==3.1.50
      - gwas-sumstats-tools>=1.0.24
      - idna==3.17
      - markdown-it-py==4.2.0
      - mdurl==0.1.2
      - mypy_extensions==1.1.0
      - numpy==2.4.6
      - packaging==26.2
      - pandas==2.3.3
      - pandera==0.31.1
      - petl==1.7.18
      - psutil==7.2.2
      - pyarrow==24.0.0
      - pydantic==2.13.4
      - pydantic_core==2.46.4
      - Pygments==2.20.0
      - pyliftover==0.4.1
      - pysam==0.24.0
      - python-dateutil==2.9.0.post0
      - pytz==2026.2
      - PyYAML==6.0.3
      - ratelimiter==1.2.0.post0
      - requests==2.34.2
      - rich==15.0.0
      - ruamel.yaml==0.19.1
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.3
      - toposort==1.10
      - typeguard==4.5.2
      - typer==0.26.4
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - typing_extensions==4.15.0
      - tzdata==2026.2
      - urllib3==2.7.0
